version: 2
jobs:
  build:
    docker:
    - image: circleci/node:9.11
    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v2-cache-root-{{ checksum "yarn.lock" }}
        - v2-cache-root-

    - run: yarn
    - run: yarn run build

    - save_cache:
        key: v2-cache-root-{{ checksum "yarn.lock" }}
        paths:
        - node_modules

    - run: yarn test
